name: Validate PR Description

on:
  pull_request:
    types:
      [
        opened,
        synchronize,
        reopened,
        labeled,
        unlabeled,
        edited,
        ready_for_review,
        converted_to_draft,
      ]

permissions:
  contents: read

jobs:
  check:
    # Don't check the Version Packages PR
    if: github.head_ref != 'changeset-release/main'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-add-pr
      cancel-in-progress: true
    timeout-minutes: 30
    name: Check
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            everything_but_markdown:
              - '!**/*.md'

      - name: Install Dependencies
        if: steps.changes.outputs.everything_but_markdown == 'true'
        uses: ./.github/actions/install-dependencies

      - name: List changed files
        if: steps.changes.outputs.everything_but_markdown == 'true'
        id: files
        uses: Ana06/get-changed-files@25f79e676e7ea1868813e21465014798211fad8c # v2.3.0
        with:
          format: "json"

      - name: Test PR description validation
        if: steps.changes.outputs.everything_but_markdown == 'true'
        run: pnpm tsx --test tools/deployments/validate-pr-description.test.ts

      - run: pnpm tsx tools/deployments/validate-pr-description.ts
        if: steps.changes.outputs.everything_but_markdown == 'true'
        env:
          TITLE: ${{ github.event.pull_request.title }}
          BODY: ${{ github.event.pull_request.body }}
          LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
          FILES: ${{ steps.files.outputs.all }}
          DRAFT: ${{ github.event.pull_request.draft }}
